{"name": "test_log_fail", "status": "passed", "start": 1638028381659, "stop": 1638028381660, "uuid": "31188f5c-944b-4935-84b4-606dbba2476d", "historyId": "1c8ef04b5efb530f297c008febc65861", "testCaseId": "7ca6e908bf6479da7772d77349e0c8d1", "fullName": "test_allure_login.TestLogin#test_log_fail", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录失败"}, {"name": "suite", "value": "test_allure_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-U9QUJNK"}, {"name": "thread", "value": "8536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_login"}], "links": [{"type": "test_case", "url": "https://github.com/qameta/allure-integrations/issues/8#issuecomment-268313637", "name": "Test case title"}]}