{"name": "test_login_success", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  -1\n  +2", "trace": "self = <Allure_demo.test_allure_login.TestLogin object at 0x000001DAF704A1C8>\n\n    @allure.story(\"登录成功\")\n    def test_login_success(self):\n        with allure.step(\"step1:打开应用\"):\n            print(\"打开应用\")\n        with allure.step(\"step2:进入登录页面\"):\n            print(\"登录页面\")\n        with allure.step(\"step3:输入用户名和密码\"):\n>           assert 1==2\nE           assert 1 == 2\nE             -1\nE             +2\n\ntest_allure_login.py:27: AssertionError"}, "steps": [{"name": "step1:打开应用", "status": "passed", "start": 1638028143281, "stop": 1638028143281}, {"name": "step2:进入登录页面", "status": "passed", "start": 1638028143281, "stop": 1638028143281}, {"name": "step3:输入用户名和密码", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  -1\n  +2\n", "trace": "  File \"D:\\Python_H\\Allure_demo\\test_allure_login.py\", line 27, in test_login_success\n    assert 1==2\n"}, "start": 1638028143281, "stop": 1638028143282}], "start": 1638028143281, "stop": 1638028143282, "uuid": "7736a411-3a37-406c-9646-b208c2a4e72f", "historyId": "97af97840558b7ea3cea560b7225cf28", "testCaseId": "f0f4987af6850fdc0149fa3047031f32", "fullName": "test_allure_login.TestLogin#test_login_success", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录成功"}, {"name": "suite", "value": "test_allure_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-U9QUJNK"}, {"name": "thread", "value": "17324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_login"}]}